from .platforms.MobileScreen.mobile_screen import HomeMobileScreenView
from .platforms.TabletScreen.tablet_screen import HomeTabletScreenView
from .platforms.DesktopScreen.desktop_screen import DesktopScreenView
